import Head from "next/head";

const NewHead = (props) => {
	const {title, keywords} = props

	return (
		<Head>
			<title>{title}</title>
			<meta name="keywords" content={keywords} />
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<link rel="icon" href="/favicon.ico" />
		</Head>
	)
}
export default NewHead